-- 创建通知公告表
CREATE TABLE public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('official', 'common', 'industry')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 添加行级安全策略，默认关闭所有操作
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

-- 创建触发器以自动更新updated_at字段
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_notices_updated_at
    BEFORE UPDATE ON public.notices
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- 创建RLS策略：允许匿名用户查看公告
CREATE POLICY "允许匿名用户查看公告" ON public.notices
    FOR SELECT 
    TO anon
    USING (true);

-- 创建RLS策略：允许已登录用户查看公告
CREATE POLICY "允许已登录用户查看公告" ON public.notices
    FOR SELECT 
    TO authenticated
    USING (true);

-- 创建RLS策略：只有已登录用户可以创建公告
CREATE POLICY "只有已登录用户可以创建公告" ON public.notices
    FOR INSERT 
    TO authenticated
    WITH CHECK (true);

-- 创建RLS策略：只有已登录用户可以更新自己创建的公告
CREATE POLICY "只有已登录用户可以更新公告" ON public.notices
    FOR UPDATE 
    TO authenticated
    USING (true);

-- 创建RLS策略：只有已登录用户可以删除公告
CREATE POLICY "只有已登录用户可以删除公告" ON public.notices
    FOR DELETE 
    TO authenticated
    USING (true);

-- 添加索引以提高查询性能
CREATE INDEX notices_category_idx ON public.notices (category);
CREATE INDEX notices_created_at_idx ON public.notices (created_at DESC);

-- 为notices表添加注释
COMMENT ON TABLE public.notices IS '存储所有类型的公告信息';
COMMENT ON COLUMN public.notices.id IS '公告的唯一标识符';
COMMENT ON COLUMN public.notices.title IS '公告标题';
COMMENT ON COLUMN public.notices.content IS '公告内容';
COMMENT ON COLUMN public.notices.category IS '公告分类：官方公告(official)、常知公告(common)、行业资讯(industry)';
COMMENT ON COLUMN public.notices.created_at IS '公告创建时间';
COMMENT ON COLUMN public.notices.updated_at IS '公告最后更新时间';

-- 添加示例数据
INSERT INTO public.notices (title, content, category) VALUES
('无忧IP新版2.0大大更新说明', '我们很高兴地宣布无忧IP新版2.0已正式发布！此次更新包含多项重要功能改进和性能优化...', 'official'),
('新增地区', '无忧IP现已新增支持以下地区：澳大利亚、新西兰、加拿大等多个国家和地区。用户现在可以使用这些地区的IP进行各类操作...', 'official'),
('澳洲代理使用频率高被封IP', '近期我们发现澳洲地区的IP因使用频率过高而被封禁的情况有所增加。为避免IP被封，建议用户在使用澳洲代理时注意以下几点...', 'common'),
('全球代理使用频率要求', '为保证所有用户都能获得稳定的服务体验，无忧IP对全球代理的使用频率有一定要求。请遵循以下指南...', 'common'),
('无忧IP，海外IP多节点助力爬虫数据收集', '对于需要大规模数据采集的企业来说，IP资源的质量和数量是决定项目成功的关键因素。无忧IP提供的海外多节点服务如何助力爬虫数据收集？...', 'industry'),
('什么是网络隐身,代理IP是如何实现的', '在当今数字时代，网络隐身已成为保护个人隐私和数据安全的重要手段。代理IP作为实现网络隐身的核心技术，其工作原理和应用场景值得深入了解...', 'industry');

-- 配置存储桶
-- 如果需要存储相关文件，可以创建存储桶
INSERT INTO storage.buckets (id, name, public) VALUES ('notices-attachments', '公告附件', true);

-- 创建存储桶的安全策略
CREATE POLICY "公开访问公告附件" ON storage.objects
    FOR SELECT
    TO anon
    USING (bucket_id = 'notices-attachments');

CREATE POLICY "已登录用户可以上传公告附件" ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'notices-attachments');

CREATE POLICY "已登录用户可以更新公告附件" ON storage.objects
    FOR UPDATE
    TO authenticated
    USING (bucket_id = 'notices-attachments');

CREATE POLICY "已登录用户可以删除公告附件" ON storage.objects
    FOR DELETE
    TO authenticated
    USING (bucket_id = 'notices-attachments'); 